### ISSUE TITLE
Replace gettimeofday in sysclock with clock_gettime

### ISSUE THREAD

**Issue by AngusJull** [CarletonURocketry/fetcher#38]
clock_gettime is a POSIX way of doing things, gettimeofday is deprecated in newer versions of QNX, and it allows selection of different clocks. An example use of clock_gettime can be found in `m10spg.c`.

**Comment by linguini1** [comment]
It's deprecated? It's also in the POSIX standard. Must have missed this in Steve's slides lol

**Comment by AngusJull** [comment]
Yeah I guess my language is kinda wrong there. The suggestion is based on [this page](https://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.lib_ref/topic/g/gettimeofday.html), and some answers I was reading on the internet.

**Comment by linguini1** [comment]
Finished in #54
